---

  # Check the GVL directories exist, and chown them to ubuntu
  - name: "Check /mnt/gvl directory exists"
    file: name="/mnt/gvl" state=directory owner=ubuntu group=ubuntu
    sudo: yes
    sudo_user: root

  - name: "Check /mnt/gvl/apps directory exists"
    file: name="/mnt/gvl/apps" state=directory owner=ubuntu group=ubuntu
    sudo: yes
    sudo_user: root

  # Create the directory for the war file to go in.
  - name: "Create apollo directory - target"
    file: path="{{ apollo_home }}/target" state=directory owner=ubuntu group=ubuntu recurse=yes

  # Create the directory for the scripts.
  - name: "Create apollo directory - scripts"
    file: path="{{ apollo_home }}/scripts" state=directory owner=ubuntu group=ubuntu

  # Install Tomcat7, Ant, and Tomcat7-admin (just in case we need admin console)
  - name: "Install Tomcat and Ant"
    apt: pkg={{ item }} state=installed
    become: yes
    with_items:
        - tomcat7
        - tomcat7-admin
        - ant

  # Set environment variables inside profile and bashrc files
  # This probably isn't needed, but just in case
  - name: "Setting environment variables"
    become: yes
    ignore_errors: yes
    lineinfile: dest="{{ item[0] }}" line="{{ item[1] }}" state=present
    with_nested:
      - ["/home/ubuntu/.bashrc", "/home/ubuntu/.profile", "/root/.bashrc", "/root/.profile", "/home/researcher/.bashrc", "/home/researcher/.profile"]
      - ["export TOMCAT_HOME=/var/lib/tomcat7/",
         "export CATALINA_HOME=/usr/share/tomcat7",
         "export CATALINA_BASE=/var/lib/tomcat7"]

  # Set environment variables - source bashrc
  - name: "Source ~/.bashrc"
    shell: source /home/ubuntu/.bashrc
    become_user: ubuntu
    args:
      executable: /bin/bash

  # Increase memory for tomcat7
  # This is a requirement for Web Apollo, or it will crash
  - name: "Increase memory for tomcat"
    copy: src="setenv.sh" dest="/usr/share/tomcat7/bin" owner=tomcat7 mode=0755
    become: yes

  # Set JAVA_HOME inside the tomcat config.
  - name: "Set JAVA_HOME in tomcat7 config"
    copy: src="tomcat7" dest="/etc/default/tomcat7" owner=tomcat7 mode=0755
    become: yes

  # Create a new database user, database_user
  - name: "Create the database postgres user"
    command: sudo -u postgres bash -c "psql -c \"CREATE USER {{ database_user }} WITH PASSWORD '{{ database_pass }}';\""
    ignore_errors: yes
    args:
      chdir: "{{ apollo_home }}"

  - name: "Create the database postgres user"
    command: sudo -u postgres bash -c "psql -c \"CREATE USER {{ database_user_chado }} WITH PASSWORD '{{ database_pass }}';\""
    ignore_errors: yes
    args:
      chdir: "{{ apollo_home }}"

  # Ensure the directory for the database exists - owned by postgres
  - name: "Create database directory"
    file: path="{{ apollo_home }}/db" state=directory owner=postgres group=postgres mode=777

  # Make sure postgres uses that location - create the gvl_apollo tablespace
  - name: "Make postgres aware of the new database location"
    command: sudo -u postgres bash -c "psql -c \"CREATE TABLESPACE gvl_apollo LOCATION '{{ apollo_home }}/db/'\""
    ignore_errors: yes
    args:
      chdir: "{{ apollo_home }}"

  # Create the production database, apollo-production
  - name: "Create main production database"
    command: sudo su postgres -c "createdb -E UTF-8 -D gvl_apollo -O {{ database_user }} {{ database_prod }}"
    ignore_errors: yes
    args:
      chdir: "{{ apollo_home }}"

  # Create the production database, apollo-production
  - name: "Create chado database"
    command: sudo su postgres -c "createdb -E UTF-8 -D gvl_apollo -O {{ database_user_chado }} {{ database_prod_chado }}"
    ignore_errors: yes
    args:
      chdir: "{{ apollo_home }}"

  - name: "Copy the script file across"
    copy: src="load_chado_schema.sh" dest="{{ apollo_home }}/scripts/load_chado_schema.sh" owner=ubuntu mode=0755
    become: yes

  - name: "Copy the script file across"
    copy: src="chado-schema-with-ontologies.sql.gz" dest="{{ apollo_home }}/scripts/chado-schema-with-ontologies.sql.gz" owner=ubuntu mode=777
    become: yes

  - name: "Load chado schema"
    shell: "./load_chado_schema.sh -u database_user_chado -d apollo-production-chado -h localhost -p 5432 -s chado-schema-with-ontologies.sql.gz"
    become: yes
    become_user: ubuntu
    environment:
      PGPASSWORD: "postgres_password"
    args:
      chdir: "{{ apollo_home }}/scripts"
      executable: /bin/bash

  ## DEPLOY APOLLO ##
  # Download the apollo war file into target directory.
  - name: "Download apollo war file"
    get_url: url=https://swift.rc.nectar.org.au:8888/v1/AUTH_377/cloudman-gvl-410/webapollo/apollo.war dest="{{ apollo_home }}/target/apollo.war" owner=ubuntu mode=0755 checksum=md5:BDC5FAE1823D0DA7ED751026F0919B96

  # Remove the default webapp files so we never see the splash screen
  - name: "Remove default webapp files"
    file: path=/var/lib/tomcat7/webapps/ROOT state=absent

  # Copy files for tomcat (server.xml)
  - name: "Copy server.xml to correct place"
    template: src=server.xml.j2 dest="{{ tomcat_config }}/server.xml" owner=tomcat7 mode=0600

  # Restart Tomcat
  - name: "Restart tomcat7"
    service: name=tomcat7 state=restarted
    become: yes
    become_user: root

  # Add file to nginx folder to get tomcat and nginx to talk nicely
  - name: "Copy nginx config file"
    copy: src="apollo.locations" dest="{{ nginx_config }}/apollo.locations" mode=0600
    become: yes

  # Restart Nginx to apply changes
  - name: "restart nginx"
    service: name=nginx state=restarted
